ELEVATOR:
  FLOORS: 10
  INITIAL_FLOOR: 1
  TIME_TO_GO_UP_ONE_FLOOR: 5
  TIME_TO_GO_DOWN_ONE_FLOOR: 5
  TIME_TO_OPEN_DOORS: 5
  TIME_TO_CLOSE_DOORS: 5

SIMULATION:
  SIMULATION_FILE: demand_simulation/random_scenario/sim_1.csv

ALGORITHM:
  ALGORITHM_FILE: "123"
